### ISSUE TITLE
whitelist IPv6 /64

### ISSUE THREAD

**Issue by MarcusWolschon** [mawis/couriergrey#1]
practical example:
GMail tries to deliver with different IPv6 adresses from the same /64 subnet in every attempt.
Even for a single senter host this will happen if IPv6 privacy extensions are enable in the sending host.

What happens:
Couriergrey greylists every single adress and thus the message never gets delivered.

What should happen:
couriergrey should make database entries for an entire /64 and not individual IPv6 hosts.

**Comment by mawis** [comment]
Mailservers sending mail from a cluster with different IP addresses is one of the reasons we have the possibility to pre-define a white list. This problem is not special to IPv6, it happens with IPv4 clusters as well.
As in IPv4 there is no way to correctly guess the network size used in IPv6. There are providers, that only assign smaller networks of even individual IPv6 addresses to customers. For example whitelisting a complete /64 could result in opening a complete network of dial-up users if one of them sends an e-mail using a self-operated mail server.
On the other hand there is also no guarantee the all addresses of the cluster are within a /64. A mail provider could also send the mails using different distributed exit-servers located in different networks.

So I think it's correct to only add the individual address to the database. But I'm thinking about adding an option for users that want to have it differently.

**Comment by MarcusWolschon** [comment]
a)Providers are advised to assign a /56 and never assign anything smaller then a /64.
That what is assigned even to individual hosts in hosting facilities.
If a user wants to add a /64 individually adding 2 Billion entries is not an option.

b)Your answer does not explain why you would not want to add an **example to the file** to tell users how to do this. It is already possible but you have to experiment to find the correct syntax.
